# Generated by Django 5.0.6 on 2024-07-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(),
        ),
    ]
